server:
  port: 8080

spring:
  application:
    name: adminApplication
  profiles:
    #对应参数（dev:开发环境、local:本地环境、prod:生产环境、test:测试环境）
    #设置对应环境的参数时可以加载对应配置文件
    active: dev

---
#静态资源映射 start
#优先级从高到底：/META-INF/resources、/resources、/static、/public 这些全部映射到 /**
spring:
  web:
    resources:
      static-locations:
        classpath:/META-INF/resources,
        classpath:/resources,
        classpath:/static,
        classpath:/public,
        classpath:/public/welcome

#静态资源映射 end

---
# freemarker start
spring:
  freemarker:
#    template-loader-path: classpath:/templates/
    #指定Freemarker模板文件的后缀名
    suffix: .ftl
    settings:
#      #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
      template_update_delay: 0
#      #incompatible_improvements: 2.3.34
#      #模板异常处理器
#      template_exception_handler: rethrow
#      #是否强制使用绝对路径
#      classic_compatible: false
#      #去掉多余的空格，非常有用（默认为true）
#      whitespace_stripping: true
#      #控制是否显示错误提示
#      show_error_tips: true
#      #中国
#      locale: zh_CN
#      #编码utf8
#      default_encoding: UTF-8
#      #输出文件编码utf8
#      output_encoding: UTF-8
#      #url编码utf8
#      url_escaping_charset: UTF-8
#      #显示日期格式
#      date_format: yyyy-MM-dd
#      #显示时间格式
#      time_format: HH:mm:ss
#      #显示日期格式
#      datetime_format: yyyy-MM-dd HH:mm:ss
#      #数字显示格式
#      number_format: "#.####"
# freemarker end

---
# datasource start
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54323/test
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
  # datasource end

---
# jpa start
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
# jpa end

#---
## mybatis start
#mybatis:
#  #持久层接口对应sql文件目录
#  mapper-locations: classpath*:mapper/**/*.xml
#  #表对应实体类包路径
#  type-aliases-package: org.example.model
#  #下划线转托峰命名
#  configuration:
#    map-underscore-to-camel-case: true
## mybatis end
#
#---


---
# mybatis-plus start
mybatis-plus:
  #持久层接口对应sql文件目录
  mapper-locations: classpath*:mapper/**/*.xml
  #表对应实体类包路径
  type-aliases-package: org.example.model
  #下划线转托峰命名
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

# mybatis-plus end
---


#logging start
logging:
  file:
    path: /home/usr/local/temp/logs
  logback:
    rollingpolicy:
      max-size: 1MB
      max-history: 30
      total-size-cap: 1GB
#logging end